---
title: "Marco Zanotti's Resume"
author: Marco Zanotti
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
  lang:
    value: 'en'
  resume:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results = 'asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("R/cv_printing_functions.r")

if (params$lang == "en") {
  Sys.setlocale("LC_ALL", "us")
} else {
  Sys.setlocale("LC_ALL", "Italian_Italy.1252")
}

# Read in all data and initialize a CV printer object
cv <- create_cv_object(
  data_location = "https://docs.google.com/spreadsheets/d/1FwVp14baq9CeUS2x8nniXf9tBCBc3hJJxbbH3DDZziY/edit?usp=sharing", 
  resume = params$resume
  ) %>% 
  clean_cv_object(language = params$lang)
```

```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if (params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```



Aside
================================================================================

```{r contacts}
if (params$lang == "en") {
  cat("#### Contacts {#contact}\n")
} else {
  cat("#### Contatti {#contact}\n")
}
cv %>% print_contacts()
```

```{r statistics}
if (params$lang == "en") {
  cat("#### Statistics\n")
} else {
  cat("#### Statistica\n")
}
cv %>% print_text_block("statistics_skills_aside")
```

```{r programming}
if (params$lang == "en") {
  cat("#### Programming\n")
} else {
  cat("#### Programmazione\n")
}
cv %>% print_skill_bars(section_id = "programming")
```

```{r versioning}
if (params$lang == "en") {
  cat("#### Versioning\n")
} else {
  cat("#### Versioning\n")
}
cv %>% print_skill_bars(section_id = "versioning")
```

```{r ci_cd}
if (params$lang == "en") {
  cat("#### CI / CD\n")
} else {
  cat("#### CI / CD\n")
}
cv %>% print_skill_bars(section_id = "integration")
```

```{r cloud}
if (params$lang == "en") {
  cat("#### Cloud\n")
} else {
  cat("#### Cloud\n")
}
cv %>% print_skill_bars(section_id = "cloud")
```

```{r languages}
if (params$lang == "en") {
  cat("#### Languages\n")
} else {
  cat("#### Lingue\n")
}
cv %>% print_skill_bars(section_id = "language")
```
  
&nbsp;  
    
&nbsp;  
  
```{r disclaimer}
if (params$lang == "en") {
  cat(
"Made with the R package [**pagedown**](https://github.com/rstudio/pagedown).  
  
*Last updated on *"
)
} else {
  cat(
"Creato con il pacchetto R [**pagedown**](https://github.com/rstudio/pagedown).  
  
*Aggiornato a *"
)
}
```
*`r stringr::str_to_title(format(Sys.time(), '%B %Y'))`*



Main
================================================================================

Marco Zanotti {#title}
--------------------------------------------------------------------------------

```{r}
cv %>% print_text_block("introduction") 
```


```{r professional_experience}
if (params$lang == "en") {
  cat("## Professional Experience {data-icon=suitcase}\n")
} else {
  cat("## Esperienza Professionale {data-icon=suitcase}\n")
}
cv %>% print_experience("professional_experience")
```


```{r teaching_experience}
if (params$lang == "en") {
  cat("## Teaching Experience {data-icon=chalkboard-teacher}\n")
} else {
  cat("## Insegnamento {data-icon=chalkboard-teacher}\n")
}
cv %>% print_experience("teaching_experience")
```


```{r publications}
if (params$lang == "en") {
  cat("## Publications {data-icon=book-open}\n")
} else {
  cat("## Pubblicazioni {data-icon=book-open}\n")
}
cv %>% print_experience("publication")
```


```{r education}
if (params$lang == "en") {
  cat("## Education {data-icon=graduation-cap}\n")
} else {
  cat("## Istruzione {data-icon=graduation-cap}\n")
}
cv %>% print_experience("education")
```
